# Generated by Django 6.0.2 on 2026-02-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('description', models.TextField(blank=True, null=True, verbose_name='文件描述')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmsapp.userinfo', verbose_name='上传人')),
            ],
            options={
                'verbose_name': '项目文件',
                'verbose_name_plural': '项目文件',
                'db_table': 't_project_file',
                'ordering': ['-upload_date'],
            },
        ),
    ]
