# Generated by Django 6.0.2 on 2026-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0002_projectfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='project_cycle',
            field=models.IntegerField(default=0, verbose_name='项目周期'),
        ),
    ]
