# Generated by Django 5.2.12 on 2026-03-31 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0006_upgrade_log_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradelog',
            name='log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upgradelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_logs', to='pmsapp.userinfo'),
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('rule_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='规则ID')),
                ('rule_name', models.CharField(max_length=64, verbose_name='规则名称')),
                ('trigger_type', models.CharField(choices=[('task_overdue', '任务逾期'), ('task_completed', '任务完成'), ('budget_exceeded', '预算超支'), ('schedule_delayed', '进度延迟'), ('daily', '每日触发'), ('weekly', '每周触发'), ('manual', '手动触发')], max_length=32, verbose_name='触发类型')),
                ('trigger_condition', models.TextField(blank=True, null=True, verbose_name='触发条件')),
                ('action_type', models.CharField(choices=[('send_notification', '发送通知'), ('create_reminder', '创建提醒'), ('update_status', '更新状态'), ('generate_report', '生成报告'), ('call_ai', '调用AI')], max_length=32, verbose_name='动作类型')),
                ('action_config', models.TextField(blank=True, null=True, verbose_name='动作配置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_rules', to='pmsapp.userinfo', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '工作流规则',
                'verbose_name_plural': '工作流规则',
                'db_table': 't_workflow_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('history_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='历史记录ID')),
                ('session_id', models.CharField(max_length=64, verbose_name='会话ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_history', to='pmsapp.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI对话历史',
                'verbose_name_plural': 'AI对话历史',
                'db_table': 't_ai_chat_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'session_id'], name='t_ai_chat_h_user_id_c4225b_idx'), models.Index(fields=['created_at'], name='t_ai_chat_h_created_67cb8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('alert_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='预警ID')),
                ('alert_type', models.CharField(choices=[('task_overdue', '任务逾期'), ('budget_exceeded', '预算超支'), ('schedule_delayed', '进度延迟')], max_length=32, verbose_name='预警类型')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=16, verbose_name='风险等级')),
                ('description', models.TextField(verbose_name='描述')),
                ('suggestion', models.TextField(blank=True, null=True, verbose_name='建议')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='pmsapp.projectinfo', verbose_name='项目')),
            ],
            options={
                'verbose_name': '风险预警',
                'verbose_name_plural': '风险预警',
                'db_table': 't_risk_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'is_resolved'], name='t_risk_aler_project_21e6f2_idx'), models.Index(fields=['risk_level'], name='t_risk_aler_risk_le_a80de2_idx'), models.Index(fields=['created_at'], name='t_risk_aler_created_7bd861_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('log_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='日志ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='执行状态')),
                ('trigger_data', models.TextField(blank=True, null=True, verbose_name='触发数据')),
                ('result', models.TextField(blank=True, null=True, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='pmsapp.workflowrule', verbose_name='关联规则')),
            ],
            options={
                'verbose_name': '工作流日志',
                'verbose_name_plural': '工作流日志',
                'db_table': 't_workflow_log',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['rule', 'executed_at'], name='t_workflow__rule_id_f0eac7_idx'), models.Index(fields=['status'], name='t_workflow__status_2b4164_idx')],
            },
        ),
    ]
