# Generated by Django 6.0.2 on 2026-02-27 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('project_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('project_name', models.CharField(max_length=64, unique=True, verbose_name='项目名称')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('project_cycle', models.IntegerField(verbose_name='项目周期')),
                ('key_content_count', models.IntegerField(default=0, verbose_name='关键内容数量')),
                ('completed_count', models.IntegerField(default=0, verbose_name='已完成数量')),
                ('in_progress_count', models.IntegerField(default=0, verbose_name='进行中数量')),
                ('not_started_count', models.IntegerField(default=0, verbose_name='未开始数量')),
                ('completion_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='完成进度')),
                ('project_status', models.CharField(choices=[('未开始', '未开始'), ('进行中', '进行中'), ('已完成', '已完成'), ('逾期未完结', '逾期未完结')], default='未开始', max_length=16, verbose_name='项目状态')),
                ('milestone_length', models.IntegerField(blank=True, null=True, verbose_name='里程碑项目长度')),
                ('milestone_completed_length', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='里程碑完成长度')),
                ('milestone_height', models.IntegerField(blank=True, null=True, verbose_name='里程碑项目高度')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 't_project_info',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('responsible_count', models.IntegerField(default=0, verbose_name='负责关键内容数量')),
                ('completed_task_count', models.IntegerField(default=0, verbose_name='已完成任务数')),
                ('in_progress_task_count', models.IntegerField(default=0, verbose_name='进行中任务数')),
                ('not_started_task_count', models.IntegerField(default=0, verbose_name='未开始任务数')),
                ('team_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='所属团队')),
                ('contact_info', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '人员信息',
                'verbose_name_plural': '人员信息',
                'db_table': 't_user_info',
            },
        ),
        migrations.CreateModel(
            name='BudgetCost',
            fields=[
                ('budget_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='预算ID')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('project_manager', models.CharField(max_length=32, verbose_name='负责人')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('workday_count', models.IntegerField(verbose_name='工作日天数')),
                ('participant_count', models.IntegerField(verbose_name='投入人数')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='总预算金额')),
                ('personnel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='人员成本')),
                ('rnd_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='研发成本')),
                ('design_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='设计成本')),
                ('travel_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='差旅成本')),
                ('marketing_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='市场推广成本')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='总成本')),
                ('remaining_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='剩余预算金额')),
                ('cost_remark', models.TextField(blank=True, null=True, verbose_name='成本说明')),
                ('cost_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='成本分类占比')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='pmsapp.projectinfo', verbose_name='项目ID')),
            ],
            options={
                'verbose_name': '预算成本',
                'verbose_name_plural': '预算成本',
                'db_table': 't_budget_cost',
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('task_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('key_content_name', models.CharField(max_length=64, verbose_name='关键内容名称')),
                ('priority_level', models.CharField(choices=[('优先级1', '优先级1（最高）'), ('优先级2', '优先级2'), ('优先级3', '优先级3'), ('优先级4', '优先级4（最低）')], default='优先级3', max_length=16, verbose_name='紧急程度')),
                ('plan_start_date', models.DateField(verbose_name='计划开始时间')),
                ('plan_end_date', models.DateField(verbose_name='计划结束时间')),
                ('task_cycle', models.IntegerField(verbose_name='任务周期')),
                ('time_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='时间进度')),
                ('task_status', models.CharField(choices=[('已完成', '已完成'), ('进行中', '进行中'), ('未开始', '未开始')], default='未开始', max_length=16, verbose_name='任务状态')),
                ('actual_complete_date', models.DateField(blank=True, null=True, verbose_name='实际完成时间')),
                ('completion_reminder', models.CharField(blank=True, max_length=64, null=True, verbose_name='完成提醒')),
                ('completion_remark', models.TextField(blank=True, null=True, verbose_name='完成情况备注')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pmsapp.projectinfo', verbose_name='项目ID')),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pmsapp.userinfo', verbose_name='负责人')),
            ],
            options={
                'verbose_name': '任务信息',
                'verbose_name_plural': '任务信息',
                'db_table': 't_task_info',
                'ordering': ['priority_level', 'plan_end_date'],
            },
        ),
        migrations.CreateModel(
            name='QuadrantTask',
            fields=[
                ('quadrant_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='象限ID')),
                ('stat_cycle', models.CharField(choices=[('今日', '今日'), ('本周', '本周'), ('本月', '本月')], default='本月', max_length=16, verbose_name='统计周期')),
                ('quadrant_type', models.CharField(choices=[('优先级1-重要紧急', '重要紧急'), ('优先级2-重要不紧急', '重要不紧急'), ('优先级3-紧急不重要', '紧急不重要'), ('优先级4-不紧急不重要', '不紧急不重要')], max_length=32, verbose_name='象限类型')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('key_content_name', models.CharField(max_length=64, verbose_name='关键内容名称')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('task_status', models.CharField(choices=[('已完成', '已完成'), ('进行中', '进行中'), ('未开始', '未开始')], max_length=16, verbose_name='任务状态')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmsapp.projectinfo', verbose_name='项目ID')),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_quadrant_tasks', to='pmsapp.userinfo', verbose_name='负责人')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadrant_tasks', to='pmsapp.userinfo', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '四象限任务',
                'verbose_name_plural': '四象限任务',
                'db_table': 't_quadrant_task',
            },
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='pmsapp.userinfo', verbose_name='负责人'),
        ),
        migrations.CreateModel(
            name='DailyReminder',
            fields=[
                ('reminder_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='提醒ID')),
                ('reminder_date', models.DateField(verbose_name='日期')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('key_content_name', models.CharField(max_length=64, verbose_name='关键内容名称')),
                ('task_type', models.CharField(choices=[('今日开始', '今日开始'), ('今日截止', '今日截止'), ('已逾期', '已逾期'), ('周期内未完成', '周期内未完成')], max_length=16, verbose_name='任务类型')),
                ('task_status', models.CharField(choices=[('已完成', '已完成'), ('进行中', '进行中'), ('未开始', '未开始')], max_length=16, verbose_name='任务状态')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmsapp.projectinfo', verbose_name='项目ID')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pmsapp.userinfo', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '日待办提醒',
                'verbose_name_plural': '日待办提醒',
                'db_table': 't_daily_reminder',
                'ordering': ['-reminder_date', 'task_type'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('plan_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='计划ID')),
                ('plan_week', models.CharField(max_length=16, verbose_name='计划周期')),
                ('monday_task', models.TextField(blank=True, null=True, verbose_name='星期一任务')),
                ('tuesday_task', models.TextField(blank=True, null=True, verbose_name='星期二任务')),
                ('wednesday_task', models.TextField(blank=True, null=True, verbose_name='星期三任务')),
                ('thursday_task', models.TextField(blank=True, null=True, verbose_name='星期四任务')),
                ('friday_task', models.TextField(blank=True, null=True, verbose_name='星期五任务')),
                ('saturday_task', models.TextField(blank=True, null=True, verbose_name='星期六任务')),
                ('sunday_task', models.TextField(blank=True, null=True, verbose_name='星期日任务')),
                ('completed_count', models.IntegerField(default=0, verbose_name='已完成任务数')),
                ('in_progress_count', models.IntegerField(default=0, verbose_name='进行中任务数')),
                ('not_started_count', models.IntegerField(default=0, verbose_name='未开始任务数')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='pmsapp.userinfo', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '周工作计划',
                'verbose_name_plural': '周工作计划',
                'db_table': 't_weekly_plan',
                'ordering': ['-plan_week'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('summary_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='总结ID')),
                ('summary_week', models.CharField(max_length=16, verbose_name='总结周期')),
                ('completed_work', models.TextField(blank=True, null=True, verbose_name='本周已完成工作')),
                ('uncompleted_work', models.TextField(blank=True, null=True, verbose_name='本周截止未完成工作')),
                ('next_week_plan', models.TextField(blank=True, null=True, verbose_name='下周工作计划')),
                ('problems_suggestions', models.TextField(blank=True, null=True, verbose_name='问题与建议')),
                ('completed_count', models.IntegerField(default=0, verbose_name='已完成任务数')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='pmsapp.userinfo', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '周工作总结',
                'verbose_name_plural': '周工作总结',
                'db_table': 't_weekly_summary',
                'ordering': ['-summary_week'],
            },
        ),
    ]
