# Generated by Django 6.0.2 on 2026-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsapp', '0003_alter_projectinfo_project_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('ai', 'AI配置'), ('email', '邮件配置'), ('security', '安全设置')], max_length=20, verbose_name='设置类型')),
                ('setting_key', models.CharField(max_length=64, verbose_name='设置键')),
                ('setting_value', models.TextField(blank=True, verbose_name='设置值')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 't_system_settings',
                'unique_together': {('setting_type', 'setting_key')},
            },
        ),
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                ('team_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='团队ID')),
                ('team_name', models.CharField(max_length=64, unique=True, verbose_name='团队名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='pmsapp.userinfo', verbose_name='成员')),
            ],
            options={
                'verbose_name': '团队组',
                'verbose_name_plural': '团队组',
                'db_table': 't_team_group',
            },
        ),
    ]
